language: node_js
cache: yarn
node_js:
  - 11
  - 12

before_script:
  - psql -c 'create database vgoscam_test;' -U postgres

env:
  - NODE_ENV=test
  - DB_USERNAME=postgres
  - DB_PASSWORD=
  - DB_DATABASE=vgoscam_test
  - DB_HOST=localhost
  - DB_PORT=5432
  - DB_DIALECT=postgres
  - DB_DRIVER=pg

script:
  - yarn run lint
  - yarn test

services:
  - postgresql
