version: '3'

services:
  api:
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  web:
    restart: always
    build: .
    ports:
    environment:
      - NODE_ENV=development

  db:
    image: postgres:11

  db-data:


  redis:
    image: redis

