version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "5858:5858"
      - "8080:8080"
      - "35729:35729"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes_from:
      - web-data

  web-data:
    build: .
    entrypoint: /bin/true
    volumes:

  db:
    image: mongo:3.6

  db-data:

  redis:

